### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by hasufell** [hasufell/file-io#1]
`ReadWriteMode` seems to misbehave?

**Comment by joeyh** [comment]
I'm considering using this to replace FilePath code that uses ReadWriteMode and I'm curious how it misbehaves on windows?

**Comment by hasufell** [comment]
I don't remember. It was reviewed by the directory maintainer and the Win32 maintainer. I'm guessing this must be fixed.

**Comment by hasufell** [comment]
I couldn't produce any discrepancy from the regular `openBinaryFile` anymore.
