### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by Bodigrim** [hasufell/file-io#13]
I realised that `file-io` is missing both from Stackage [LTS 22.0](https://www.stackage.org/lts-22.0) and [Nightly](https://www.stackage.org/nightly-2023-12-18). Could it please be added?

**Comment by Bodigrim** [comment]
@hasufell packages are not added automatically, most likely you have to edit https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml yourself. (BTW `os-string` is also missing)

**Comment by hasufell** [comment]
https://github.com/commercialhaskell/stackage/pull/7286
