### ISSUE TITLE
Should file-io use a more permissive dwShareMode on Windows?

### ISSUE THREAD

**Issue by Rufflewind** [hasufell/file-io#20]
Noticed one diff while trying to migrate directory to file-io:

- directory uses **maxShareMode** for `openFileForRead`, whereas
- file-io uses **FILE_SHARE_READ** for `openFile _ ReadMode`.

I think the main consequence is that it would cause `openFile` block other programs from trying to write or delete the file if it is being read.

I tend to default to a permissive dwShareMode since that's more POSIX-like and avoids frustrating users with [errors like](https://superuser.com/questions/1039567/this-action-cannot-be-completed-because-the-file-is-open-in-another-application):

> The action can't be completed because the folder or a file in it is open in another program

**Comment by hasufell** [comment]
Can we write a reproducer test case?

Then I don't mind the change.

**Comment by hasufell** [comment]
Oh actually... this is on purpose and posix *does not* allow this either. I have written tests for it:

https://github.com/hasufell/file-io/blob/d2b5ed203d8cf0a0c51dabcb85ffe72f6f662da3/tests/Properties.hs#L109-L117

You have to open it in `ReadWrite` instead, which has max sharemode:

https://github.com/hasufell/file-io/blob/d2b5ed203d8cf0a0c51dabcb85ffe72f6f662da3/windows/System/File/Platform.hsc#L68-L72

**Comment by Rufflewind** [comment]
Thanks for the clarification.

> this is on purpose and posix *does not* allow this either.

Looks like it is an intended quirk of GHC in the construction of a `Handle` from a file descriptor: https://hackage.haskell.org/package/ghc-internal-9.1001.0/docs/src//GHC.Internal.IO.FD.html#mkFD

```hs
        -- regular files need to be locked
        RegularFile -> do
           -- On Windows we need an additional call to get a unique device id
           -- and inode, since fstat just returns 0 for both.
           -- See also Note [RTS File locking]
           (unique_dev, unique_ino) <- getUniqueFileInfo fd dev ino
           r <- lockFile (fromIntegral fd) unique_dev unique_ino
                         (fromBool write)
           when (r == -1)  $
                ioException (IOError Nothing ResourceBusy "openFile"
                                   "file is locked" Nothing Nothing)
```

Unfortunate, but I guess this is just something users of Haskell have to live with.

> You have to open it in `ReadWrite` instead, which has max sharemode:

That would require write privileges, which might be unavailable.

**Comment by hasufell** [comment]
> That would require write privileges, which might be unavailable.

Again, we can export more non-basey things from Internal modules.

But I'm not sure how much we gain from that if directory is the only package doing "the right thing".

A CLC proposal might be the way forward instead.
