### ISSUE TITLE
Should O_CLOEXEC be set on POSIX?

### ISSUE THREAD

**Issue by Rufflewind** [hasufell/file-io#21]
Another diff observed while trying to migrate directory to file-io (https://github.com/hasufell/file-io/issues/4#issue-1365527787):

Should files opened by file-io set [O_CLOEXEC](https://hackage.haskell.org/package/unix-2.8.5.1/docs/System-Posix-IO.html#v:cloexec) to prevent them from being inherited by child processes?

**Comment by hasufell** [comment]
I think we discussed this already in https://github.com/hasufell/file-io/pull/5 and the verdict was that this library tries to stay as close to base behavior as possible.

You can use [setCloseOnExec](https://hackage.haskell.org/package/ghc-internal-9.1001.0/docs/GHC-Internal-System-Posix-Internals.html#v:setCloseOnExec) explicitly.

**Comment by Rufflewind** [comment]
> You can use [setCloseOnExec](https://hackage.haskell.org/package/ghc-internal-9.1001.0/docs/GHC-Internal-System-Posix-Internals.html#v:setCloseOnExec) explicitly.

It isn't thread-safe since another thread can fork the executable between open and setCloseOnExec.

**Comment by hasufell** [comment]
We can provide a variant `openFileWithCloseOnExec`, possibly through a `.Internal` module.

Internal modules still follow PVP, but may not have deprecation periods.

**Comment by Rufflewind** [comment]
Sounds good.

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/file-io-0.1.2/candidate

**Comment by Rufflewind** [comment]
Updated https://github.com/haskell/directory/pull/179 to use `openFileWithCloseOnExec`: https://github.com/haskell/directory/pull/179/files#diff-cc810a2a20a0b2c54800a706eb4890b14eff0d57b2777d520d64a0c73fa7f140R247

**Comment by hasufell** [comment]
Published it: https://hackage.haskell.org/package/file-io-0.1.2
