### ISSUE TITLE
openBinaryFile creates the file if it does not exist

### ISSUE THREAD

**Issue by Rufflewind** [hasufell/file-io#4]
`openFile` sets `creat` (`O_CREAT`) even for `ReadOnly :: IOMode`.

https://github.com/hasufell/file-io/blob/6cc5a118946611e0df030d31141814fb0d3c868a/System/File/Common.hs#L14-L15

https://github.com/hasufell/file-io/blob/6cc5a118946611e0df030d31141814fb0d3c868a/System/File/Posix.hs#L13-L21

This behavior is inconsistent with `System.IO.openBinaryFile` ([`read_flags`](https://hackage.haskell.org/package/base-4.17.0.0/docs/src/GHC.IO.FD.html#read_flags)).

Note: It might also be a good idea to use `cloexec` (`O_CLOEXEC`) to prevent child processes from inheriting the file descriptors.

I noticed this bug in `directory`, which caused `copyFile` to create the source file if it does not exist. This was fixed in https://github.com/haskell/directory/commit/154a29c9fd2dddaa830faee66d84df528a92199c, along with `O_CLOEXEC` in https://github.com/haskell/directory/commit/0ff4e13f1f51234fe047b4bc1ca60e567afd0c36.

**Comment by hasufell** [comment]
Good catch.

**Comment by Bodigrim** [comment]
@hasufell could this be closed? Seems completed.
