### ISSUE TITLE
openFile is not exception safe

### ISSUE THREAD

**Issue by treeowl** [hasufell/file-io#8]
If someone opens a file without masking exceptions, then (on a bad day) the file could be opened but no finalizer created to close it. That breaks the typical user expectation that dropping a `Handle` will eventually close the associated file descriptor. I fixed a related issue in `base` a while back, though I don't remember the details. Arguably the whole idea of automatically closing files is a bad one, but consistency seems important.

**Comment by hasufell** [comment]
@Mistuke

**Comment by Mistuke** [comment]
I don't believe the programming model was to rely on finalizers to close handles. The non determinism of when this happens can cause a number of issues.

As far as I'm aware of the automatic Handle cleanup is a last ditch effort to prevent resource leaking but not something to be relied upon. At least that's what I've alway used as the model.

**Comment by treeowl** [comment]
@Mistuke So do you think we just shouldn't put finalizers on handles?

**Comment by treeowl** [comment]
@Mistuke It sounded like you thought it isn't a bug that `openFile` isn't exception safe, but now I can't tell .... If it's interrupted by an asynchronous exception, then there's no way whatever to close the file without exiting the program.

**Comment by Mistuke** [comment]
Sorry for the confusion. That `openFile` isn't exception safe is a valid bug. But I think that should an exception happen in openFile there should be no handle at all (which might be what you're saying?) 

That's because I don't think
> That breaks the typical user expectation that dropping a Handle will eventually close the associated file descriptor.

Is a valid expectation to have. But as you say users expect it, so we should try to get it to work as much as possible.

**Comment by treeowl** [comment]
If you look at what I did in `base`, that's one approach. Not necessarily the prettiest. the point is that we want to be sure to mask exceptions until we've installed the finalizer.

**Comment by hasufell** [comment]
I'm still not sure what is your proposal exactly. I don't know what you did in base.

**Comment by treeowl** [comment]
Here's the code to look at. See the explanation above it.

https://hackage.haskell.org/package/base-4.17.0.0/docs/src/GHC.IO.Handle.FD.html#withOpenFile%27

**Comment by treeowl** [comment]
Also read the stuff at `openFileWith`, which that uses.

**Comment by Bodigrim** [comment]
Breadcrumbs:
* The patch for `base` landed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4681
* It was supposed to fix several issues, including https://gitlab.haskell.org/ghc/ghc/-/issues/19114

**Comment by Bodigrim** [comment]
This works:
```haskell
{-# LANGUAGE QuasiQuotes #-}

module Main where

import Control.Concurrent
import Control.Monad
import qualified Data.ByteString.Lazy as BL
import System.File.OsPath
import System.IO
import System.OsPath

main :: IO ()
main = replicateM_ 100000 $ do
  let fn = "test.txt"
  thr <- forkIO (System.IO.readFile fn >>= putStr)
  threadDelay 1
  void $ killThread thr
```

This fails with `test.txt: withFile': resource exhausted (Too many open files)`, even after #11:
```haskell
{-# LANGUAGE QuasiQuotes #-}

module Main where

import Control.Concurrent
import Control.Monad
import qualified Data.ByteString.Lazy as BL
import System.File.OsPath
import System.IO
import System.OsPath

main :: IO ()
main = replicateM_ 100000 $ do
  let fn = [osp|test.txt|]
  thr <- forkIO (System.File.OsPath.readFile fn >>= BL.putStr)
  threadDelay 1
  void $ killThread thr
```

**Comment by treeowl** [comment]
Whoops... It looks like I forgot the part where `openFile` needs to get changed, and only did some other stuff around there. I'll have to page this back in and try to look at it this week (probably this coming weekend, due to travel).

**Comment by hasufell** [comment]
Yes I'm aware we still leak the file descriptors (although Handles don't with the patch). I'll fix that shortly.

**Comment by hasufell** [comment]
I believe it is fixed now: https://github.com/hasufell/file-io/pull/11
